# Generated by Django 5.0 on 2024-05-20 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="description",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="start_date",
        ),
        migrations.AddField(
            model_name="budget",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="budget",
            name="position",
            field=models.CharField(
                choices=[
                    ("SURPLUS", "Surplus"),
                    ("DEFICIT", "Deficit"),
                    ("EQUAL", "Equal"),
                ],
                default="EQUAL",
                max_length=64,
            ),
        ),
    ]
