# Generated by Django 5.0 on 2024-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0003_remove_income_description_alter_income_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(),
        ),
    ]
