# Generated by Django 5.0 on 2024-05-21 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0004_alter_budget_date_alter_income_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="remaining_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="budget",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
