# Generated by Django 5.0 on 2024-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fin_manager_app",
            "0005_budget_remaining_income_budget_total_expenses_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
