# Generated by Django 5.0 on 2024-05-27 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0006_alter_income_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
