# Generated by Django 5.0 on 2024-06-17 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_incurred",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
