# Generated by Django 5.0 on 2024-07-24 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager_app", "0011_monthlyexpense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="month",
        ),
        migrations.RemoveField(
            model_name="monthlyexpense",
            name="year",
        ),
        migrations.RemoveField(
            model_name="monthlyincome",
            name="month",
        ),
        migrations.RemoveField(
            model_name="monthlyincome",
            name="year",
        ),
        migrations.AddField(
            model_name="monthlyexpense",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 24, 18, 28, 51, 507583, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 24, 18, 28, 22, 582911, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
