# Generated by Django 5.0 on 2024-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager_app", "0012_remove_monthlyexpense_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(),
        ),
    ]
