# Generated by Django 5.0 on 2024-07-26 12:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager_app", "0014_alter_monthlyexpense_date_alter_monthlyincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 26, 12, 57, 41, 964859, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
