# Generated by Django 5.0 on 2024-07-26 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_manager_app", "0015_alter_monthlyexpense_date_alter_monthlyincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
