# Generated by Django 5.0 on 2024-07-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0016_alter_monthlyincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("SALARY", "Salary"),
                    ("ROI", "Return on Investment"),
                    ("GIFTS", "Gifts"),
                    ("OTHERS", "Others"),
                    ("LOAN", "Loan"),
                ],
                default="NONE",
                max_length=64,
            ),
        ),
    ]
