# Generated by Django 5.0 on 2024-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0017_alter_income_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(),
        ),
    ]
