# Generated by Django 5.0 on 2024-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager_app", "0018_alter_monthlyexpense_date_alter_monthlyincome_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyexpense",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="monthlyincome",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
